In [1]:
l1 = [1,2,3,4,6,8,5,9,7]

9

In [3]:
# to add + 2 to all elements in l1
l1_new = []
for i in l1:
    l1_new.append(i+2)
l1_new

[3, 4, 5, 6, 8, 10, 7, 11, 9]

In [7]:
# using numpy arrary
import numpy as np
a1 = np.array([1,2,3,4,6,8,5,9,7])

In [9]:
a1+2

array([ 3,  4,  5,  6,  8, 10,  7, 11,  9])

In [10]:
# np array is homogeneous in nature
# it will store only one datatype in an array, it will convert the datatypes of values as necessary
# in normal list all datatypes will be preserved
a2 = np.array(['Anik',12,3.5,True])
a2

array(['Anik', '12', '3.5', 'True'], dtype='<U32')

# Numpy

### Why Numpy ?
It is used for performing operations like array addition, substraction,
multiplication, to create some random numbers, create dummy values etc.

### List vs Array
1. In list, we cannot do element - wise operation but in array we can.
2. Array to List conversion is possible and also List to array conversion is also possible,
but we will lose the dimensions.
3. List is heterogenous datatype but Numpy is a homogenous datatype.

In [24]:
arr1 = np.array([[2, 5, 8, 9],
                 [1, 4, 5, 0]])
arr1

array([[2, 5, 8, 9],
       [1, 4, 5, 0]])

In [15]:
arr1.shape

(2, 4)

In [16]:
# total no. of elements in array
arr1.size

8

In [17]:
# dimension of an array
arr1.ndim

2

In [18]:
arr1.dtype

dtype('int64')

In [19]:
type(arr1)

numpy.ndarray

In [20]:
tl1 = list(arr1)
tl1

[array([2, 5, 8, 9]), array([1, 4, 5, 0])]

In [25]:
tarr1 = np.array(tl1)
tarr1

array([[2, 5, 8, 9],
       [1, 4, 5, 0]])

In [26]:
arr1

array([[2, 5, 8, 9],
       [1, 4, 5, 0]])

In [31]:
# making the 2 elements into single
flaten = arr1.flatten()
flaten

array([2, 5, 8, 9, 1, 4, 5, 0])

In [32]:
a = list(flaten)
a

[np.int64(2),
 np.int64(5),
 np.int64(8),
 np.int64(9),
 np.int64(1),
 np.int64(4),
 np.int64(5),
 np.int64(0)]

In [35]:
y = np.array([[1,5],[9,5]])
y

array([[1, 5],
       [9, 5]])

In [34]:
x = np.array([[4,7],[2,6]])
x

array([[4, 7],
       [2, 6]])

In [36]:
y + 2

array([[ 3,  7],
       [11,  7]])

In [37]:
x + y

array([[ 5, 12],
       [11, 11]])

In [38]:
# matrix multiplication
np.matmul(x,y)

array([[67, 55],
       [56, 40]])

In [41]:
# create one 6 x 4 array

big_arr = np.array([[23, 45, 11, 39],
                    [18, 27, 49, 12],
                    [34, 10, 41, 22],
                    [15, 37, 28, 44],
                    [19, 33, 25, 30],
                    [40, 21, 17, 13]])
big_arr

array([[23, 45, 11, 39],
       [18, 27, 49, 12],
       [34, 10, 41, 22],
       [15, 37, 28, 44],
       [19, 33, 25, 30],
       [40, 21, 17, 13]])

In [43]:
big_arr2 = np.random.randint(1,40,size=(6,4))
big_arr2

array([[29, 38,  7, 13],
       [24, 26,  8, 18],
       [21, 12,  8, 27],
       [39, 32, 16, 24],
       [35, 23, 21,  4],
       [37, 31, 19, 11]], dtype=int32)

In [44]:
big_arr2.size

24

In [50]:
# reshape array to other formats
big_arr2.reshape(4,6)

array([[29, 38,  7, 13, 24, 26],
       [ 8, 18, 21, 12,  8, 27],
       [39, 32, 16, 24, 35, 23],
       [21,  4, 37, 31, 19, 11]], dtype=int32)

In [51]:
# column wise reading
big_arr2.reshape(4,6,order='F')

array([[29, 35, 12,  7, 21, 27],
       [24, 37, 32,  8, 19, 24],
       [21, 38, 23,  8, 13,  4],
       [39, 26, 31, 16, 18, 11]], dtype=int32)