In [5]:
'''
1️⃣ Sales Data Analysis

A company recorded daily sales for 30 days.

Create a NumPy array of 30 random sales values between 1000 and 5000 and calculate:

Total sales

Average sales

Top 5 highest sales days
'''
import pandas as pd
import numpy as np

arr_sales = np.random.randint(1000,5001,size=30)
arr_sales

array([3429, 1794, 2170, 4284, 4089, 4474, 2918, 3134, 3713, 1028, 4901,
       2413, 2938, 1784, 2380, 3101, 2735, 1774, 2534, 1334, 4792, 1564,
       3446, 3585, 3646, 2232, 1628, 2153, 4969, 1109], dtype=int32)

In [6]:
# total sales
np.sum(arr_sales)

np.int64(86051)

In [9]:
# avg sales
np.average(arr_sales).round(2)

np.float64(2868.37)

In [10]:
np.mean(arr_sales).round(2)

np.float64(2868.37)

In [12]:
# top 5 sales dates
top5 = np.argsort(arr_sales)[-5:][::-1]
top5

array([28, 10, 20,  5,  3])

In [13]:
top5_sales = arr_sales[top5]
top5_sales

array([4969, 4901, 4792, 4474, 4284], dtype=int32)

In [14]:
# top 5 days
print('Top 5 highest sales days')
for i in range(5):
    print(f'Day {top5[i] + 1} = Sales {top5_sales[i]}') # since day strt frm 0 in python indexes

Top 5 highest sales days
Day 29 = Sales 4969
Day 11 = Sales 4901
Day 21 = Sales 4792
Day 6 = Sales 4474
Day 4 = Sales 4284


In [15]:
'''
2. Outlier Detection
Generate 100 random numbers between 10 and 100.
Find outliers using Z-score method.
'''
arr_rand_nums = np.random.randint(10,101,size=100)
arr_rand_nums

array([ 96,  33,  80,  63,  42,  68,  27,  46,  35,  76,  21,  30,  94,
       100,  89,  19,  80,  18,  86,  18,  78,  56,  61,  65,  82,  64,
        16,  60,  78,  26,  51,  67,  69,  34,  92,  69,  54,  14,  74,
        56,  11,  66,  52,  84,  59,  16,  85, 100,  39,  63,  90,  21,
        90,  96,  25,  91,  54,  25,  74,  60,  38,  32,  52,  37,  86,
        92,  72,  48,  35,  24,  51,  25,  97,  94,  34,  93,  20,  53,
        44,  90,  91,  16,  54,  62,  10,  49,  59,  38,  23,  59,  50,
        86,  64,  22,  42,  69,  50,  56,  73,  63], dtype=int32)

In [20]:
# mean and standard deviation
mean = np.mean(arr_rand_nums)
std = np.std(arr_rand_nums)

In [21]:
# z-score
z_score = (arr_rand_nums-mean)/std

In [22]:
# identify outliers / |Z| > 3 is common threshold
outliers = arr_rand_nums[np.abs(z_score) > 3]


In [24]:
print("Data:\n", arr_rand_nums)
print("\nMean:", mean)
print("Standard Deviation:", std)
print("\nZ-scores:\n", z_score)

print("\nOutliers (Z > 3 or Z < -3):", outliers)

Data:
 [ 96  33  80  63  42  68  27  46  35  76  21  30  94 100  89  19  80  18
  86  18  78  56  61  65  82  64  16  60  78  26  51  67  69  34  92  69
  54  14  74  56  11  66  52  84  59  16  85 100  39  63  90  21  90  96
  25  91  54  25  74  60  38  32  52  37  86  92  72  48  35  24  51  25
  97  94  34  93  20  53  44  90  91  16  54  62  10  49  59  38  23  59
  50  86  64  22  42  69  50  56  73  63]

Mean: 56.41
Standard Deviation: 25.516306550909754

Z-scores:
 [ 1.55155684 -0.91745253  0.92450684  0.25826622 -0.56473691  0.45421934
 -1.15259628 -0.40797441 -0.83907128  0.76774434 -1.38774003 -1.0350244
  1.47317559  1.70831934  1.27722247 -1.46612128  0.92450684 -1.5053119
  1.15965059 -1.5053119   0.84612559 -0.01606816  0.17988497  0.33664747
  1.00288809  0.29745684 -1.58369315  0.14069434  0.84612559 -1.1917869
 -0.21202128  0.41502872  0.49340997 -0.87826191  1.39479434  0.49340997
 -0.09444941 -1.6620744   0.68936309 -0.01606816 -1.77964628  0.37583809
 -0.17283066  

In [ ]:
'''
3. Data Normalization
Given the dataset:
[120, 150, 200, 250, 300]
Normalize the values using Min-Max Scaling (0–1).
'''


In [29]:
# mix-max scaling
d = np.array([120, 150, 200, 250, 300])

d_min = np.min(d)
d_max = np.max(d)

# minmax
minmax = (d - d_min)/ (d_max - d_min)
minmax

array([0.        , 0.16666667, 0.44444444, 0.72222222, 1.        ])

In [31]:
'''
4.  Customer Age Analysis
Customer ages dataset:
[18,22,25,30,35,40,45,50,55,60]
Find:
Mean age
Median age
Standard deviation
'''

age = np.array([18,22,25,30,35,40,45,50,55,60])
mean_age = np.mean(age)
median_age = np.median(age)
std_age = np.std(age)
print(f'Mean age: {mean_age} Median age: {median_age} Standard deviation: {std_age}')

Mean age: 38.0 Median age: 37.5 Standard deviation: 13.66747965061591


In [34]:
'''
5.Matrix Row Filtering
Generate a 10×5 matrix.
Select rows where the row sum is greater than 200.
'''
m_array = np.random.randint(10,100,size = (10,5))
for i in m_array:
    sum_row = np.sum(i)
    if sum_row > 200:
        print(i)

[24 69 63 28 69]
[49 36 94 99 89]
[33 66 22 48 87]
[98 53 33 72 80]
[25 65 29 16 71]
[44 86 17 76 62]
[12 90 30 52 55]
[22 94 63 30 94]
[17 18 92 47 29]


In [36]:
'''
6. Feature Scaling
Create an array of 50 random numbers (1–100).
Standardize the data using:
(x - mean) / standard deviation
'''

data = np.random.randint(1,101,size = 50)
m = np.mean(data)
s = np.std(data)

# standardized mean= 0 and sd = 1
standarzied = (data - m)/s
standarzied

array([ 1.47548405, -1.29061087,  1.37044247,  1.30041475,  0.35504054,
       -0.83543069,  0.28501282,  0.63515141,  0.88024843, -0.66036139,
        1.05531773, -0.59033367,  1.12534545,  1.26540089, -0.38025052,
       -0.59033367, -0.76540297,  0.14495738, -0.83543069,  0.88024843,
        0.07492966,  0.53010984,  1.37044247,  0.32002668, -1.43066631,
       -0.73038911,  1.16035931, -0.06512578, -0.06512578,  1.51049791,
        0.60013755,  1.09033159,  1.61553948, -1.39565245,  0.24999896,
       -1.36063859,  0.32002668,  0.49509598,  1.51049791, -1.36063859,
       -1.39565245, -1.08052771, -1.18556929, -1.32562473,  0.35504054,
       -0.66036139,  0.00490194, -1.25559701, -1.53570788, -1.18556929])

In [37]:
# new mean
m_new = np.mean(standarzied)
print(m_new)
s_new = np.std(standarzied)
print(s_new)

8.881784197001253e-18
0.9999999999999999
