In [5]:
'''
1️⃣ Sales Data Analysis

A company recorded daily sales for 30 days.

Create a NumPy array of 30 random sales values between 1000 and 5000 and calculate:

Total sales

Average sales

Top 5 highest sales days
'''
import pandas as pd
import numpy as np

arr_sales = np.random.randint(1000,5001,size=30)
arr_sales

array([3429, 1794, 2170, 4284, 4089, 4474, 2918, 3134, 3713, 1028, 4901,
       2413, 2938, 1784, 2380, 3101, 2735, 1774, 2534, 1334, 4792, 1564,
       3446, 3585, 3646, 2232, 1628, 2153, 4969, 1109], dtype=int32)

In [6]:
# total sales
np.sum(arr_sales)

np.int64(86051)

In [9]:
# avg sales
np.average(arr_sales).round(2)

np.float64(2868.37)

In [10]:
np.mean(arr_sales).round(2)

np.float64(2868.37)

In [12]:
# top 5 sales dates
top5 = np.argsort(arr_sales)[-5:][::-1]
top5

array([28, 10, 20,  5,  3])

In [13]:
top5_sales = arr_sales[top5]
top5_sales

array([4969, 4901, 4792, 4474, 4284], dtype=int32)

In [14]:
# top 5 days
print('Top 5 highest sales days')
for i in range(5):
    print(f'Day {top5[i] + 1} = Sales {top5_sales[i]}') # since day strt frm 0 in python indexes

Top 5 highest sales days
Day 29 = Sales 4969
Day 11 = Sales 4901
Day 21 = Sales 4792
Day 6 = Sales 4474
Day 4 = Sales 4284


In [15]:
'''
2. Outlier Detection
Generate 100 random numbers between 10 and 100.
Find outliers using Z-score method.
'''
arr_rand_nums = np.random.randint(10,101,size=100)
arr_rand_nums

array([ 96,  33,  80,  63,  42,  68,  27,  46,  35,  76,  21,  30,  94,
       100,  89,  19,  80,  18,  86,  18,  78,  56,  61,  65,  82,  64,
        16,  60,  78,  26,  51,  67,  69,  34,  92,  69,  54,  14,  74,
        56,  11,  66,  52,  84,  59,  16,  85, 100,  39,  63,  90,  21,
        90,  96,  25,  91,  54,  25,  74,  60,  38,  32,  52,  37,  86,
        92,  72,  48,  35,  24,  51,  25,  97,  94,  34,  93,  20,  53,
        44,  90,  91,  16,  54,  62,  10,  49,  59,  38,  23,  59,  50,
        86,  64,  22,  42,  69,  50,  56,  73,  63], dtype=int32)

In [20]:
# mean and standard deviation
mean = np.mean(arr_rand_nums)
std = np.std(arr_rand_nums)

In [21]:
# z-score
z_score = (arr_rand_nums-mean)/std

In [22]:
# identify outliers / |Z| > 3 is common threshold
outliers = arr_rand_nums[np.abs(z_score) > 3]


In [24]:
print("Data:\n", arr_rand_nums)
print("\nMean:", mean)
print("Standard Deviation:", std)
print("\nZ-scores:\n", z_score)

print("\nOutliers (Z > 3 or Z < -3):", outliers)

Data:
 [ 96  33  80  63  42  68  27  46  35  76  21  30  94 100  89  19  80  18
  86  18  78  56  61  65  82  64  16  60  78  26  51  67  69  34  92  69
  54  14  74  56  11  66  52  84  59  16  85 100  39  63  90  21  90  96
  25  91  54  25  74  60  38  32  52  37  86  92  72  48  35  24  51  25
  97  94  34  93  20  53  44  90  91  16  54  62  10  49  59  38  23  59
  50  86  64  22  42  69  50  56  73  63]

Mean: 56.41
Standard Deviation: 25.516306550909754

Z-scores:
 [ 1.55155684 -0.91745253  0.92450684  0.25826622 -0.56473691  0.45421934
 -1.15259628 -0.40797441 -0.83907128  0.76774434 -1.38774003 -1.0350244
  1.47317559  1.70831934  1.27722247 -1.46612128  0.92450684 -1.5053119
  1.15965059 -1.5053119   0.84612559 -0.01606816  0.17988497  0.33664747
  1.00288809  0.29745684 -1.58369315  0.14069434  0.84612559 -1.1917869
 -0.21202128  0.41502872  0.49340997 -0.87826191  1.39479434  0.49340997
 -0.09444941 -1.6620744   0.68936309 -0.01606816 -1.77964628  0.37583809
 -0.17283066  

In [ ]:
'''
3. Data Normalization
Given the dataset:
[120, 150, 200, 250, 300]
Normalize the values using Min-Max Scaling (0–1).
'''


In [29]:
# mix-max scaling
d = np.array([120, 150, 200, 250, 300])

d_min = np.min(d)
d_max = np.max(d)

# minmax
minmax = (d - d_min)/ (d_max - d_min)
minmax

array([0.        , 0.16666667, 0.44444444, 0.72222222, 1.        ])

In [31]:
'''
4.  Customer Age Analysis
Customer ages dataset:
[18,22,25,30,35,40,45,50,55,60]
Find:
Mean age
Median age
Standard deviation
'''

age = np.array([18,22,25,30,35,40,45,50,55,60])
mean_age = np.mean(age)
median_age = np.median(age)
std_age = np.std(age)
print(f'Mean age: {mean_age} Median age: {median_age} Standard deviation: {std_age}')

Mean age: 38.0 Median age: 37.5 Standard deviation: 13.66747965061591


In [34]:
'''
5.Matrix Row Filtering
Generate a 10×5 matrix.
Select rows where the row sum is greater than 200.
'''
m_array = np.random.randint(10,100,size = (10,5))
for i in m_array:
    sum_row = np.sum(i)
    if sum_row > 200:
        print(i)

[24 69 63 28 69]
[49 36 94 99 89]
[33 66 22 48 87]
[98 53 33 72 80]
[25 65 29 16 71]
[44 86 17 76 62]
[12 90 30 52 55]
[22 94 63 30 94]
[17 18 92 47 29]


In [36]:
'''
6. Feature Scaling
Create an array of 50 random numbers (1–100).
Standardize the data using:
(x - mean) / standard deviation
'''

data = np.random.randint(1,101,size = 50)
m = np.mean(data)
s = np.std(data)

# standardized mean= 0 and sd = 1
standarzied = (data - m)/s
standarzied

array([ 1.47548405, -1.29061087,  1.37044247,  1.30041475,  0.35504054,
       -0.83543069,  0.28501282,  0.63515141,  0.88024843, -0.66036139,
        1.05531773, -0.59033367,  1.12534545,  1.26540089, -0.38025052,
       -0.59033367, -0.76540297,  0.14495738, -0.83543069,  0.88024843,
        0.07492966,  0.53010984,  1.37044247,  0.32002668, -1.43066631,
       -0.73038911,  1.16035931, -0.06512578, -0.06512578,  1.51049791,
        0.60013755,  1.09033159,  1.61553948, -1.39565245,  0.24999896,
       -1.36063859,  0.32002668,  0.49509598,  1.51049791, -1.36063859,
       -1.39565245, -1.08052771, -1.18556929, -1.32562473,  0.35504054,
       -0.66036139,  0.00490194, -1.25559701, -1.53570788, -1.18556929])

In [37]:
# new mean
m_new = np.mean(standarzied)
print(m_new)
s_new = np.std(standarzied)
print(s_new)

8.881784197001253e-18
0.9999999999999999


In [2]:
'''
7. Replace Negative Values
Given the array:
[5, -2, 10, -8, 15, -1]
Replace all negative values with 0.
'''
import numpy as np
data1 = np.array([5, -2, 10, -8, 15, -1])

# np.where()
data2 = np.where(data1 < 0 , 0, data1)
data2

array([ 5,  0, 10,  0, 15,  0])

In [3]:
# np.clip
data3 = np.clip(data1, 0 ,None)
data3

array([ 5,  0, 10,  0, 15,  0])

In [8]:
'''
8. Top Performing Products
Product sales data:
[250,300,150,400,350,200]
Find:
Top 3 sales values
Index of top product
'''
pd_sales = np.array([250,300,150,400,350,200])
print(f'Top 3 sales values:\n{np.sort(pd_sales)[-3:][::-1]}')
print(f'Index of Top product:\n{np.argsort(pd_sales)[-1]}')

Top 3 sales values:
[400 350 300]
Index of Top product:
3


In [12]:
'''
9. Matrix Column Statistics
Generate a 6×4 matrix and compute:
Column mean
Column standard deviation
'''
data_matrix = np.random.randint(1,100,size = (6,4))

# col_mean
col_mean = np.mean(data_matrix,axis = 0)
#col_std
col_std = np.std(data_matrix,axis = 0)
print(f'Column mean: {col_mean} Standard deviation: {col_std}')

Column mean: [46.66666667 35.66666667 47.33333333 47.16666667] Standard deviation: [23.39990503 19.60158724 31.74726585 27.85328626]


In [13]:
'''
10. Data Reshaping
Create numbers 1–24 and reshape into:
4×6 matrix
6×4 matrix
'''

nums1 = np.arange(1,25)
nums1_4x6 = np.reshape(nums1,(4,6))
nums1_6x4 = np.reshape(nums1,(6,4))
print(nums1_4x6)
print(nums1_6x4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


# Advanced Practical Problems

In [17]:
'''
11. Conditional Filtering
Dataset:
[12,45,67,23,89,34,76]
Extract numbers:
Greater than 50
Less than 30
'''

cond_data = np.array([12,45,67,23,89,34,76])

print(f'Greater than 50: {cond_data[cond_data>50]}')
print(f'Less than 30: {cond_data[cond_data<30]}')
print(f'Both: {cond_data[(cond_data>30) & (cond_data<50)]}')

Greater than 50: [67 89 76]
Less than 30: [12 23]
Both: [45 34]


In [18]:
'''
12. Random Data Simulation
Generate 1000 normally distributed numbers with:
Mean = 50
Standard deviation = 10
Find:
Mean of generated data
Standard deviation
'''

rd_num = np.random.normal(loc=50,scale=10,size=1000)
rd_num

array([51.75123719, 64.81081074, 47.0116411 , 57.6134924 , 31.00106313,
       36.73128973, 43.21697406, 63.68408064, 50.09342141, 51.49970865,
       68.44268112, 47.00817543, 52.11078204, 41.58173215, 61.23242217,
       48.91643667, 56.66026739, 38.46049471, 49.27023478, 46.04275487,
       53.19348479, 50.0112002 , 62.45813268, 44.18691904, 36.62752425,
       55.49971462, 59.05138099, 55.31675802, 52.45652543, 69.93413901,
       62.31027634, 49.51665223, 38.7666049 , 44.03991693, 41.29247091,
       56.56316134, 40.86400422, 64.97737574, 19.20866582, 44.20698962,
       42.77164125, 54.09012072, 36.33179861, 64.86443892, 50.1838735 ,
       36.20527954, 53.44057953, 54.26895749, 52.6781484 , 36.92220034,
       43.39575116, 46.97991515, 48.66077126, 42.89364723, 57.79151321,
       53.5090859 , 61.27082162, 41.78690549, 52.04115512, 48.1746406 ,
       47.14175912, 62.33013244, 39.67669132, 48.38839333, 55.34344491,
       50.99210905, 49.11198672, 63.13789501, 52.93041872, 74.50

In [19]:
np.mean(rd_num)

np.float64(49.62172193944229)

In [20]:
np.std(rd_num)

np.float64(9.950387731849831)

In [21]:
'''
13. Diagonal Operations
Create a 5×5 matrix and calculate:
Main diagonal
Diagonal sum
'''

rand_5 = np.random.randint(1,100,size = (5,5))

# Method1
diag = np.diag(rand_5)
print(f'Main diagonal: {diag}')
print(f'Diagonal sum: {np.sum(diag)}')

Main diagonal: [19 15 21 92 27]
Diagonal sum: 174


In [25]:
# Method 2
print(f'Diagonal Sum: {np.trace(rand_5)}')

Diagonal Sum: 174


In [27]:
'''
14. Distance Calculation
Given two vectors:
A = [2,3,4]
B = [5,6,7]
Calculate the Euclidean distance.
'''

# It measures the straight-line distance between two points
import numpy as np
A = np.array([2, 3, 4])
B = np.array([5, 6, 7])
distance = np.linalg.norm(A - B)
print(distance)

5.196152422706632


In [31]:
'''
15. Duplicate Detection
Dataset:
[10,20,30,20,40,50,10,60]
Find:
Unique values
Count of each value
'''

data = np.array([10,20,30,20,40,50,10,60])

# unique values
data_unique,counts = np.unique(data,return_counts=True)

print(f'Unique values: {data_unique}')
print(f'Counts: {counts}')

# Dict
dict_data = dict(zip(data_unique,counts))
dict_data

Unique values: [10 20 30 40 50 60]
Counts: [2 2 1 1 1 1]


{np.int64(10): np.int64(2),
 np.int64(20): np.int64(2),
 np.int64(30): np.int64(1),
 np.int64(40): np.int64(1),
 np.int64(50): np.int64(1),
 np.int64(60): np.int64(1)}

In [32]:
'''
16. Row-wise Maximum
Generate a 7×5 matrix.
Find the maximum value in each row.
'''

m = np.random.randint(1,100,size = (7,5))
row_m_max  = np.max(m,axis = 1)
row_m_max

array([83, 67, 86, 85, 63, 95, 97], dtype=int32)

In [34]:
'''
17. Broadcasting Operation
Add the vector
[10,20,30]
to every row of the matrix:
[[1,2,3],
 [4,5,6],
 [7,8,9]]
'''
a = np.array([[1,2,3],
 [4,5,6],
 [7,8,9]])

vector = np.array([10,20,30])

res = a + vector
res

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [36]:
'''
18. Correlation Calculation
Generate two arrays of 50 random numbers.
Calculate the correlation coefficient between them.
'''
# It tells how strongly two variables move together
# Step 1: Generate data
x = np.random.rand(50)
y = np.random.rand(50)

# Step 2: Correlation
corr_matrix = np.corrcoef(x, y)

print("Correlation Matrix:\n", corr_matrix)

# Extract correlation value
correlation = corr_matrix[0, 1]
print("\nCorrelation Coefficient:", correlation)

Correlation Matrix:
 [[1.         0.14542439]
 [0.14542439 1.        ]]

Correlation Coefficient: 0.14542438509475925


In [37]:
'''
19. Large Dataset Statistics
Generate 10,000 random values and compute:
Mean
Median
Variance
Standard deviation
'''

data = np.random.rand(10000)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 0.5015418938218965
Median: 0.503733613313961
Variance: 0.08445311016392397
Standard Deviation: 0.29060817291315805


In [39]:
'''
20. Feature Engineering Scenario
Student scores dataset:
[55,60,72,80,90,65,70]
Create a new array where:
Scores ≥ 75 → "Pass"
Scores < 75 → "Fail"
'''
stu_data = np.array([[55,60,72,80,90,65,70]])
res = np.where(stu_data >= 75, 'Pass', 'Fail')
print(res)

[['Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail']]
